# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAadiralcarritohastaagotarproducto():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_aadiralcarritohastaagotarproducto(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1163, 1032)
    self.driver.find_element(By.LINK_TEXT, "Horno multifunción Bosch").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    element = self.driver.find_element(By.ID, "button-minus")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
    self.driver.find_element(By.ID, "button-minus").click()
  
